-- MySQL Script generated by MySQL Workbench
-- Mon Oct 15 22:53:58 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema OdontoSystem
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema OdontoSystem
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `OdontoSystem` DEFAULT CHARACTER SET utf8 ;
USE `OdontoSystem` ;

-- -----------------------------------------------------
-- Table `OdontoSystem`.`Cargo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `OdontoSystem`.`Cargo` (
  `id_cargo` INT NOT NULL AUTO_INCREMENT,
  `cargo` VARCHAR(45) NOT NULL,
  `salario` INT NOT NULL,
  PRIMARY KEY (`id_cargo`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `OdontoSystem`.`Funcionario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `OdontoSystem`.`Funcionario` (
  `id_funcionario` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  `cpf` VARCHAR(45) NOT NULL,
  `endereco` VARCHAR(45) NOT NULL,
  `id_cargo` INT NOT NULL,
  `sexo` VARCHAR(45) NOT NULL,
  `senha` VARCHAR(10) NOT NULL,
  PRIMARY KEY (`id_funcionario`),
  INDEX `fk_Funcionario_Cargo_idx` (`id_cargo` ASC),
  CONSTRAINT `fk_Funcionario_Cargo`
    FOREIGN KEY (`id_cargo`)
    REFERENCES `OdontoSystem`.`Cargo` (`id_cargo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `OdontoSystem`.`Grupo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `OdontoSystem`.`Grupo` (
  `id_grupo` INT NOT NULL AUTO_INCREMENT,
  `descricao` VARCHAR(45) NOT NULL,
  `ativo` TINYINT NOT NULL,
  PRIMARY KEY (`id_grupo`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `OdontoSystem`.`Funcionario_Grupo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `OdontoSystem`.`Funcionario_Grupo` (
  `id_funcionario_Grupo` INT NOT NULL AUTO_INCREMENT,
  `id_funcionario` INT NOT NULL,
  `id_grupo` INT NOT NULL,
  PRIMARY KEY (`id_funcionario_Grupo`),
  INDEX `fk_Funcionario_Grupo_Funcionario1_idx` (`id_funcionario` ASC),
  INDEX `fk_Funcionario_Grupo_Grupo1_idx` (`id_grupo` ASC),
  CONSTRAINT `fk_Funcionario_Grupo_Funcionario1`
    FOREIGN KEY (`id_funcionario`)
    REFERENCES `OdontoSystem`.`Funcionario` (`id_funcionario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Funcionario_Grupo_Grupo1`
    FOREIGN KEY (`id_grupo`)
    REFERENCES `OdontoSystem`.`Grupo` (`id_grupo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `OdontoSystem`.`Mensagem`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `OdontoSystem`.`Mensagem` (
  `id_mensagem` INT NOT NULL AUTO_INCREMENT,
  `mensagem` VARCHAR(45) NOT NULL,
  `data` DATE NULL,
  `id_funcionario_remetente` INT NOT NULL,
  `id_funcionario_destinatario` INT NOT NULL,
  `excluido` INT NULL,
  `assunto` VARCHAR(45) NOT NULL,
  `visualizado` INT NULL,
  PRIMARY KEY (`id_mensagem`),
  INDEX `fk_Mensagem_Funcionario1_idx` (`id_funcionario_remetente` ASC),
  INDEX `fk_Mensagem_Funcionario2_idx` (`id_funcionario_destinatario` ASC),
  CONSTRAINT `fk_Mensagem_Funcionario1`
    FOREIGN KEY (`id_funcionario_remetente`)
    REFERENCES `OdontoSystem`.`Funcionario` (`id_funcionario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Mensagem_Funcionario2`
    FOREIGN KEY (`id_funcionario_destinatario`)
    REFERENCES `OdontoSystem`.`Funcionario` (`id_funcionario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `OdontoSystem`.`Tarefa`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `OdontoSystem`.`Tarefa` (
  `id_tarefa` INT NOT NULL AUTO_INCREMENT,
  `descricao` VARCHAR(256) NOT NULL,
  `data_inicio` VARCHAR(15) NOT NULL,
  `data_fim` VARCHAR(15) NOT NULL,
  `id_funcionario_remetente` INT NOT NULL,
  `id_funcionario_destinatario` INT NOT NULL,
  `status` VARCHAR(45) NULL,
  `excluido` VARCHAR(5) NULL,
  `assunto` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_tarefa`),
  INDEX `fk_Tarefa_Funcionario1_idx` (`id_funcionario_remetente` ASC),
  INDEX `fk_Tarefa_Funcionario2_idx` (`id_funcionario_destinatario` ASC),
  CONSTRAINT `fk_Tarefa_Funcionario1`
    FOREIGN KEY (`id_funcionario_remetente`)
    REFERENCES `OdontoSystem`.`Funcionario` (`id_funcionario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Tarefa_Funcionario2`
    FOREIGN KEY (`id_funcionario_destinatario`)
    REFERENCES `OdontoSystem`.`Funcionario` (`id_funcionario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `OdontoSystem`.`Treinamento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `OdontoSystem`.`Treinamento` (
  `id_treinamento` INT NOT NULL AUTO_INCREMENT,
  `descricao` VARCHAR(45) NOT NULL,
  `id_funcionario_responsavel` INT NOT NULL,
  `id_funcionario_aluno` INT NOT NULL,
  PRIMARY KEY (`id_treinamento`),
  INDEX `fk_Treinamento_Funcionario1_idx` (`id_funcionario_responsavel` ASC),
  INDEX `fk_Treinamento_Funcionario2_idx` (`id_funcionario_aluno` ASC),
  CONSTRAINT `fk_Treinamento_Funcionario1`
    FOREIGN KEY (`id_funcionario_responsavel`)
    REFERENCES `OdontoSystem`.`Funcionario` (`id_funcionario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Treinamento_Funcionario2`
    FOREIGN KEY (`id_funcionario_aluno`)
    REFERENCES `OdontoSystem`.`Funcionario` (`id_funcionario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `OdontoSystem`.`Questao`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `OdontoSystem`.`Questao` (
  `id_questao` INT NOT NULL AUTO_INCREMENT,
  `pergunta` VARCHAR(45) NOT NULL,
  `alternativa1` VARCHAR(45) NULL,
  `alternativa2` VARCHAR(45) NULL,
  `alternativa3` VARCHAR(45) NULL,
  `alternativa4` VARCHAR(45) NULL,
  `resposta` INT NOT NULL,
  PRIMARY KEY (`id_questao`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `OdontoSystem`.`Prova`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `OdontoSystem`.`Prova` (
  `id_prova` INT NOT NULL AUTO_INCREMENT,
  `id_treinamento` INT NOT NULL,
  `id_questao` INT NOT NULL,
  PRIMARY KEY (`id_prova`),
  INDEX `fk_Prova_Treinamento1_idx` (`id_treinamento` ASC),
  INDEX `fk_Prova_Questao1_idx` (`id_questao` ASC),
  CONSTRAINT `fk_Prova_Treinamento1`
    FOREIGN KEY (`id_treinamento`)
    REFERENCES `OdontoSystem`.`Treinamento` (`id_treinamento`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Prova_Questao1`
    FOREIGN KEY (`id_questao`)
    REFERENCES `OdontoSystem`.`Questao` (`id_questao`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `OdontoSystem`.`Permissao`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `OdontoSystem`.`Permissao` (
  `id_permissao` INT NOT NULL,
  `descricao` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_permissao`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `OdontoSystem`.`Perfil`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `OdontoSystem`.`Perfil` (
  `id_perfil` INT NOT NULL,
  `id_cargo` INT NOT NULL,
  `id_permissao` INT NOT NULL,
  PRIMARY KEY (`id_perfil`, `id_cargo`, `id_permissao`),
  INDEX `fk_Perfil_Cargo1_idx` (`id_cargo` ASC),
  INDEX `fk_Perfil_Permissao1_idx` (`id_permissao` ASC),
  CONSTRAINT `fk_Perfil_Cargo1`
    FOREIGN KEY (`id_cargo`)
    REFERENCES `OdontoSystem`.`Cargo` (`id_cargo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Perfil_Permissao1`
    FOREIGN KEY (`id_permissao`)
    REFERENCES `OdontoSystem`.`Permissao` (`id_permissao`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `OdontoSystem`.`Aulas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `OdontoSystem`.`Aulas` (
  `id_aulas` INT NOT NULL,
  `aula` BINARY(100) NOT NULL,
  `id_treinamento` INT NOT NULL,
  PRIMARY KEY (`id_aulas`),
  INDEX `fk_Aulas_Treinamento1_idx` (`id_treinamento` ASC),
  CONSTRAINT `fk_Aulas_Treinamento1`
    FOREIGN KEY (`id_treinamento`)
    REFERENCES `OdontoSystem`.`Treinamento` (`id_treinamento`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
